name = "this-maybe-awesome"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "this-maybe-awesome_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "this-maybe-awesome.wasm"
command = "npm run build:release"
